fretboard:
  drawing:
      background_color:
      font_color: dimgray
      font_family: Verdana
      font_size: 24
      height: 400
      width: 300
      spacing: 30
  nut:
      color: darkslategray
      size: 10
  fret:
      color: darkgray
      size: 2
  inlays:
      color: darkslategray
      radius: 2
  string:
      color: darkslategray
      size: 3
  marker:
      border_color: black
      color: darkslategray
      font_color: white
      radius: 18
      stroke_width: 2
  title:
      font_color: dimgray
      font_family: Verdana
      font_size: 30

chord:
  string:
    muted_font_color: silver
    open_font_color: darkslategray